import {{ contractName }} from {{{ contractAddress }}}

/// This script returns returns the on-chain hash of a revealed NFT.
///
/// This hash is dynamically generated by encoding and
/// hashing the NFT serial number and salt.
///
pub fun main(id: UInt64): String? {
    if let revealedSerialNumber = {{ contractName }}.getSerialNumber(nftID: id) {
        return String.encodeHex(revealedSerialNumber.hash())
    }

    return nil
}
