// This script returns returns the on-chain hash of a revealed NFT.
//
// This hash is dynamically generated by encoding and
// hashing the NFT metadata values.
//
import {{ contractName }} from {{{ contractAddress }}}

pub fun main(id: UInt64): String? {
    if let metadata = {{ contractName }}.getMetadata(nftID: id) {
        return String.encodeHex(metadata.hash())
    }

    return nil
}
